#!/usr/bin/env python3
"""Validate local package/configuration before Docker or database operations."""
import hashlib
import json
import os
import re
import stat
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parent
IMAGE = re.compile(r'[a-z0-9][a-z0-9./:_-]{0,175}@sha256:[a-f0-9]{64}')
REQUIRED = {'01-database.sql', 'tenant.ghbf.enc', 'compose.yaml', '.env.example',
            'configure.py', 'check_release.py', 'install.sh', 'update.sh',
            'SETUP.md', 'UPDATE-RESTORE.md', 'REPORT.html', 'DELIVERY.json',
            'preflight.py', 'lifecycle.py', 'backup.sh', 'update-approval.example.json'}


def configuration():
    path = ROOT / '.env'
    if path.is_symlink() or not path.is_file():
        raise SystemExit('Create a private regular .env with configure.py first.')
    if os.name == 'posix' and stat.S_IMODE(path.stat().st_mode) & 0o077:
        raise SystemExit('Restrict destination settings first: chmod 600 .env')
    values = {}
    for line in path.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        key, separator, value = line.partition('=')
        if not separator or key in values:
            raise SystemExit('Invalid or duplicate destination setting.')
        values[key] = value.strip().strip("'\"")
    for key, value in values.items():
        if key in os.environ and os.environ[key] != value:
            raise SystemExit('Shell environment overrides destination configuration. Unset conflicting variables before continuing.')
    if any(os.environ.get(key) for key in ('COMPOSE_FILE', 'COMPOSE_ENV_FILES', 'COMPOSE_PROFILES')):
        raise SystemExit('Unset external Compose file/profile overrides for package operations.')
    for key in ('JWT_SECRET_KEY', 'SECRET_KEY', 'SETUP_CODE', 'PLATFORM_ADMIN_TOKEN'):
        if len(values.get(key, '')) < 32 or 'PLACEHOLDER' in values[key]:
            raise SystemExit('Run configure.py to generate destination-owned credentials.')
    db = urlsplit(values.get('DATABASE_URL', ''))
    if db.scheme != 'postgresql+asyncpg' or not db.hostname or not db.path.strip('/'):
        raise SystemExit('A server-only PostgreSQL database URL is required.')
    if db.port == 6543:
        raise SystemExit('Use a direct or session-pooler database connection, not transaction pooling.')
    for key in ('ADMIN_PUBLIC_URL', 'MINIAPP_PUBLIC_URL'):
        parsed = urlsplit(values.get(key, ''))
        if parsed.scheme != 'https' or not parsed.hostname or parsed.username or parsed.password:
            raise SystemExit('Public Admin and MiniApp URLs must use HTTPS without credentials.')
    if not IMAGE.fullmatch(values.get('GHBF_IMAGE', '')):
        raise SystemExit('The application image must be pinned by digest.')
    port = values.get('API_HOST_PORT', '8010')
    if not port.isdigit() or not 1024 <= int(port) <= 65535:
        raise SystemExit('Choose an unprivileged local API port between 1024 and 65535.')
    if not re.fullmatch(r'ghbf-[a-z0-9-]{4,40}', values.get('COMPOSE_PROJECT_NAME', '')):
        raise SystemExit('Use the destination-specific Compose project name generated by configure.py.')
    if port == '8000':
        raise SystemExit('Port 8000 is reserved. Choose another local API port.')
    return values


def package():
    manifest = json.loads((ROOT / 'manifest.json').read_text())
    files = manifest.get('files', {})
    if manifest.get('format') != 'ghbf-customer-package-v1' or not REQUIRED.issubset(files):
        raise SystemExit('Incomplete package manifest. Request a fresh package.')
    for name, digest in files.items():
        path = ROOT / name
        if Path(name).name != name or path.is_symlink() or not path.is_file():
            raise SystemExit('Package contains a missing or unsafe file.')
        if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise SystemExit('Package integrity mismatch. Request a fresh package; do not edit its scripts.')
    return manifest


if __name__ == '__main__':
    package()
    configuration()
    print('Local package/configuration checks completed; no connectivity or acceptance checks performed.')
