"""add_fulfillment_jobs_and_order_item_id

Revision ID: 8bfc9b56eb94
Revises: f62520a5ff1f
Create Date: 2026-09-15 04:08:11.718817

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bfc9b56eb94'
down_revision: str | Sequence[str] | None = 'f62520a5ff1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTER', name='fulfillment_job_status_enum', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fulfillment_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_fulfillment_jobs_order', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fulfillment_jobs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fulfillment_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fulfillment_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_fulfillment_jobs_tenant_status', ['tenant_id', 'status'], unique=False)

    with op.batch_alter_table('fulfillment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_item_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fulfillment_attempts_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_foreign_key('fk_fulfillment_attempts_order_item_id', 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fulfillment_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fulfillment_attempts_order_item_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fulfillment_attempts_order_item_id'))
        batch_op.drop_column('order_item_id')

    with op.batch_alter_table('fulfillment_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_fulfillment_jobs_tenant_status')
        batch_op.drop_index(batch_op.f('ix_fulfillment_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fulfillment_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_fulfillment_jobs_order_id'))
        batch_op.drop_index('ix_fulfillment_jobs_order')

    op.drop_table('fulfillment_jobs')
    # ### end Alembic commands ###
