"""add_telegram_bot_and_tenant_user_mapping

Revision ID: ed2d7cf07aaf
Revises: 714e8151eafb
Create Date: 2026-09-15 03:51:35.967712

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed2d7cf07aaf'
down_revision: str | Sequence[str] | None = '714e8151eafb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_bot_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('token_secret_ref', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_bot_id', name='uq_bot_telegram_id')
    )
    op.create_index('ix_bot_tenant_enabled', 'bots', ['tenant_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_bots_telegram_bot_id'), 'bots', ['telegram_bot_id'], unique=True)
    op.create_index(op.f('ix_bots_tenant_id'), 'bots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bots_username'), 'bots', ['username'], unique=False)
    op.create_table('tenant_telegram_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bot_id', 'telegram_user_id', name='uq_tenant_bot_telegram_user')
    )
    op.create_index('ix_tenant_bot_user', 'tenant_telegram_users', ['tenant_id', 'bot_id', 'telegram_user_id'], unique=False)
    op.create_index(op.f('ix_tenant_telegram_users_bot_id'), 'tenant_telegram_users', ['bot_id'], unique=False)
    op.create_index(op.f('ix_tenant_telegram_users_telegram_user_id'), 'tenant_telegram_users', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_tenant_telegram_users_tenant_id'), 'tenant_telegram_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_telegram_users_user_id'), 'tenant_telegram_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_telegram_users_user_id'), table_name='tenant_telegram_users')
    op.drop_index(op.f('ix_tenant_telegram_users_tenant_id'), table_name='tenant_telegram_users')
    op.drop_index(op.f('ix_tenant_telegram_users_telegram_user_id'), table_name='tenant_telegram_users')
    op.drop_index(op.f('ix_tenant_telegram_users_bot_id'), table_name='tenant_telegram_users')
    op.drop_index('ix_tenant_bot_user', table_name='tenant_telegram_users')
    op.drop_table('tenant_telegram_users')
    op.drop_index(op.f('ix_bots_username'), table_name='bots')
    op.drop_index(op.f('ix_bots_tenant_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_telegram_bot_id'), table_name='bots')
    op.drop_index('ix_bot_tenant_enabled', table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
