"""add_provider_credentials_mappings_and_fulfillment_attempts

Revision ID: f62520a5ff1f
Revises: ed2d7cf07aaf
Create Date: 2026-09-15 03:56:54.506620

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f62520a5ff1f'
down_revision: str | Sequence[str] | None = 'ed2d7cf07aaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'RETRYING', 'FAILED', 'CANCELLED', name='fulfillment_status_enum', native_enum=False), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_classification', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_fulfillment_idempotency_key')
    )
    op.create_index(op.f('ix_fulfillment_attempts_error_classification'), 'fulfillment_attempts', ['error_classification'], unique=False)
    op.create_index(op.f('ix_fulfillment_attempts_external_order_id'), 'fulfillment_attempts', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_attempts_idempotency_key'), 'fulfillment_attempts', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_fulfillment_attempts_order_id'), 'fulfillment_attempts', ['order_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_attempts_provider_id'), 'fulfillment_attempts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_attempts_tenant_id'), 'fulfillment_attempts', ['tenant_id'], unique=False)
    op.create_index('ix_fulfillment_external_order', 'fulfillment_attempts', ['provider_id', 'external_order_id'], unique=False)
    op.create_index('ix_fulfillment_tenant_order', 'fulfillment_attempts', ['tenant_id', 'order_id', 'status'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'credential_type', name='uq_provider_credential_type')
    )
    op.create_index(op.f('ix_provider_credentials_provider_id'), 'provider_credentials', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_credentials_tenant_id'), 'provider_credentials', ['tenant_id'], unique=False)
    op.create_table('provider_product_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=True),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('priority_override', sa.Integer(), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'provider_id', 'external_product_id', name='uq_tenant_prod_provider_ext')
    )
    op.create_index('ix_ppm_tenant_prod_enabled', 'provider_product_mappings', ['tenant_id', 'product_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_provider_product_mappings_external_product_id'), 'provider_product_mappings', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_provider_product_mappings_product_id'), 'provider_product_mappings', ['product_id'], unique=False)
    op.create_index(op.f('ix_provider_product_mappings_product_variant_id'), 'provider_product_mappings', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_provider_product_mappings_provider_id'), 'provider_product_mappings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_product_mappings_tenant_id'), 'provider_product_mappings', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenant_provider_configs_provider_id'), table_name='tenant_provider_configs')
    op.drop_index(op.f('ix_tenant_provider_configs_tenant_id'), table_name='tenant_provider_configs')
    op.drop_index(op.f('ix_tenant_provider_priority'), table_name='tenant_provider_configs')
    op.drop_table('tenant_provider_configs')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health_status', sa.Enum('HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN', name='provider_health_enum', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.drop_index('ix_providers_slug')
        batch_op.create_index('ix_providers_slug', ['slug'], unique=False)
        batch_op.create_index('ix_provider_tenant_enabled', ['tenant_id', 'is_enabled', 'priority'], unique=False)
        batch_op.create_index('ix_providers_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_tenant_provider_slug', ['tenant_id', 'slug'])
        batch_op.create_foreign_key('fk_providers_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_constraint('uq_tenant_provider_slug', 'providers', type_='unique')
    op.drop_index(op.f('ix_providers_tenant_id'), table_name='providers')
    op.drop_index('ix_provider_tenant_enabled', table_name='providers')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=1)
    op.drop_column('providers', 'metadata_json')
    op.drop_column('providers', 'consecutive_failures')
    op.drop_column('providers', 'health_status')
    op.drop_column('providers', 'priority')
    op.drop_column('providers', 'is_enabled')
    op.drop_column('providers', 'tenant_id')
    op.create_table('tenant_provider_configs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=32), nullable=False),
    sa.Column('provider_id', sa.CHAR(length=32), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('markup_percentage', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('health_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider_id', name=op.f('uq_tenant_provider'))
    )
    op.create_index(op.f('ix_tenant_provider_priority'), 'tenant_provider_configs', ['tenant_id', 'priority'], unique=False)
    op.create_index(op.f('ix_tenant_provider_configs_tenant_id'), 'tenant_provider_configs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_provider_configs_provider_id'), 'tenant_provider_configs', ['provider_id'], unique=False)
    op.drop_index(op.f('ix_provider_product_mappings_tenant_id'), table_name='provider_product_mappings')
    op.drop_index(op.f('ix_provider_product_mappings_provider_id'), table_name='provider_product_mappings')
    op.drop_index(op.f('ix_provider_product_mappings_product_variant_id'), table_name='provider_product_mappings')
    op.drop_index(op.f('ix_provider_product_mappings_product_id'), table_name='provider_product_mappings')
    op.drop_index(op.f('ix_provider_product_mappings_external_product_id'), table_name='provider_product_mappings')
    op.drop_index('ix_ppm_tenant_prod_enabled', table_name='provider_product_mappings')
    op.drop_table('provider_product_mappings')
    op.drop_index(op.f('ix_provider_credentials_tenant_id'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_provider_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index('ix_fulfillment_tenant_order', table_name='fulfillment_attempts')
    op.drop_index('ix_fulfillment_external_order', table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_tenant_id'), table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_provider_id'), table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_order_id'), table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_idempotency_key'), table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_external_order_id'), table_name='fulfillment_attempts')
    op.drop_index(op.f('ix_fulfillment_attempts_error_classification'), table_name='fulfillment_attempts')
    op.drop_table('fulfillment_attempts')
    # ### end Alembic commands ###
