"""Centralized models registry for Alembic and metadata reflection."""

from packages.commerce.economics_models import (
    CommercePriceQuote,
    MarkupMode,
    OrderItemEconomics,
    PricingRule,
    PricingScope,
    PricingTier,
    UserPricingTier,
)
from packages.commerce.models import Category, Order, OrderItem, Product, ProductVariant
from packages.commerce.state_machine import OrderStatus
from packages.core.database import Base
from packages.core.system_models import SystemInstallState
from packages.factory.models import BotProvisioningJob, BotProvisioningStatus
from packages.fulfillment.models import FulfillmentAttempt, FulfillmentStatus
from packages.payments.economics_models import (
    AssetLedgerTransaction,
    AssetLedgerTransactionType,
    AssetWallet,
    AutoCreditTarget,
    FlexibleDepositSession,
    FlexibleDepositStatus,
    FxPolicy,
    FxPolicyMode,
    WalletHold,
    WalletHoldStatus,
)
from packages.payments.models import (
    FinancialResolutionCase,
    FinancialResolutionCaseStatus,
    LedgerTransaction,
    PaymentAssuranceLevel,
    PaymentIntent,
    PaymentMethodConfig,
    PaymentMethodType,
    PaymentObservation,
    PaymentObservationSource,
    PaymentObservationStatus,
    PaymentProviderConfig,
    PaymentQuote,
    PaymentTransaction,
    PaymentTransactionType,
    PaymentVerificationMode,
    PaymentWebhookEvent,
    TransactionType,
    Wallet,
)
from packages.payments.state_machine import PaymentIntentStatus
from packages.providers.models import (
    Provider,
    ProviderCategory,
    ProviderCredential,
    ProviderHealthStatus,
    ProviderModel,
    ProviderOfferSnapshot,
    ProviderProductMapping,
    ProviderRoutingPolicy,
    ProviderRoutingStrategy,
)
from packages.saas.models import (
    BillingEvent,
    BillingEventStatus,
    BillingInterval,
    PlatformAuditLog,
    SaaSPlan,
    SaaSPlanPrice,
    SubscriptionStatus,
    TenantSubscription,
)
from packages.telegram.models import Bot, TenantTelegramUser
from packages.tenants.models import AuditLog, Membership, Role, Tenant, User

__all__ = [
    "AssetLedgerTransaction",
    "AssetLedgerTransactionType",
    "AssetWallet",
    "AuditLog",
    "AutoCreditTarget",
    "Base",
    "BillingEvent",
    "BillingEventStatus",
    "BillingInterval",
    "Bot",
    "BotProvisioningJob",
    "BotProvisioningStatus",
    "Category",
    "CommercePriceQuote",
    "FinancialResolutionCase",
    "FinancialResolutionCaseStatus",
    "FlexibleDepositSession",
    "FlexibleDepositStatus",
    "FulfillmentAttempt",
    "FulfillmentStatus",
    "FxPolicy",
    "FxPolicyMode",
    "LedgerTransaction",
    "MarkupMode",
    "Membership",
    "Order",
    "OrderItem",
    "OrderItemEconomics",
    "OrderStatus",
    "PaymentAssuranceLevel",
    "PaymentIntent",
    "PaymentIntentStatus",
    "PaymentMethodConfig",
    "PaymentMethodType",
    "PaymentObservation",
    "PaymentObservationSource",
    "PaymentObservationStatus",
    "PaymentProviderConfig",
    "PaymentQuote",
    "PaymentTransaction",
    "PaymentTransactionType",
    "PaymentVerificationMode",
    "PaymentWebhookEvent",
    "PlatformAuditLog",
    "PricingRule",
    "PricingScope",
    "PricingTier",
    "Product",
    "ProductVariant",
    "Provider",
    "ProviderCategory",
    "ProviderCredential",
    "ProviderHealthStatus",
    "ProviderModel",
    "ProviderOfferSnapshot",
    "ProviderProductMapping",
    "ProviderRoutingPolicy",
    "ProviderRoutingStrategy",
    "Role",
    "SaaSPlan",
    "SaaSPlanPrice",
    "SubscriptionStatus",
    "SystemInstallState",
    "Tenant",
    "TenantSubscription",
    "TenantTelegramUser",
    "TransactionType",
    "User",
    "UserPricingTier",
    "Wallet",
    "WalletHold",
    "WalletHoldStatus",
]
